name: Windows CI
on: [push]

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.9.1'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Check node modules cache
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install node modules
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn --pure-lockfile
      
    - name: cert
      shell: powershell
      run: |
          Write-Host "Import Certificate" $pfxpath = '$(Build.SourcesDirectory)\{path}\{certfile}.pfx'

          $password = '{password}'

          Add-Type -AssemblyName System.Security

          $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2

          $cert.Import($pfxpath, $password, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]"PersistKeySet")

          $store = new-object system.security.cryptography.X509Certificates.X509Store -argumentlist "MY", CurrentUser

          $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]"ReadWrite")

          $store.Add($cert)

          $store.Close()
        
    - name: yarn build
      if: steps.yarn-cache.outputs.cache-hit == 'true'
      run: |
        yarn build
        yarn tsc
    - name: Build x64 release
      shell: powershell
      run: npx react-native run-windows --arch x64 --release --no-packager --no-deploy --logging

    # Workaround for a bug in package searching during deploy.
    # The deploy script only searches windows/{*/bin/x64/Release,Release/*}, but the build step above placed the pakcages at windows/x64/Release.
    # Copy the packages to Windows/Release before deploying.
    - name: Deploy
      shell: powershell
      run: |
        Copy-Item -Path windows\x64\Release -Recurse -Destination windows\
        npx react-native run-windows --arch x64 --release --no-build --no-packager
    - name: Start Appium server
      shell: powershell
      run: Start-Process PowerShell -ArgumentList "yarn appium"

    - name: Start React server
      shell: powershell
      run: Start-Process PowerShell -ArgumentList "yarn start:windows"
      
    - name: Run tests
      run: yarn test:windows
